# docker-compose.yml

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: fb_system_dev
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data